# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Generator

def fibo(n):
	total = 0
	x = 0
	y = 1

	for n in range(n):
		prev = x
		x = y
		y = prev + x

		if (x%2==0) and (x<4000000):
			total = total + x
	yield total

for num in fibo(500):
    print(num)

# 4613732
